[package]
name = "rouxflow-standalone"
version = "0.1.0"
edition = "2021"

[dependencies]
rouxflow-core = { path = "../rouxflow-core" }
rouxflow-render = { path = "../rouxflow-render" }
rouxflow-ai = { path = "../rouxflow-ai" }
three-d = "0.17" # Match rouxflow-render version
cgmath = "0.18"
rand = "0.8"
