use crate::BitCube;
use std::fs::File;
use std::io::{Read, Write};
use std::path::Path;

pub struct PruningTable {
    pub table: Vec<u8>,
    pub size: usize,
}

impl PruningTable {
    // 3 edges (DL, FL, BL) and 2 corners (DFL, DBL)
    // Edge positions: 12P3 = 1320
    // Edge orientations: 2^3 = 8
    // Corner positions: 8P2 = 56
    // Corner orientations: 3^2 = 9
    // Total: 1320 * 8 * 56 * 9 = 5,322,240
    pub const FB_SIZE: usize = 5_322_240;
    
    // Embed the pre-calculated table at compile time.
    // Generated by `pnpm build:table` (or build.rs fallback on first compile).
    pub const FB_TABLE_BYTES: &'static [u8] = include_bytes!("../tables/fb_table.bin");

    pub fn new_fb() -> Self {
        let mut table = vec![255; Self::FB_SIZE];
        
        // Load from embedded bytes if size matches
        if Self::FB_TABLE_BYTES.len() == Self::FB_SIZE {
            table.copy_from_slice(Self::FB_TABLE_BYTES);
        } else {
            // Fallback for safety (though build should fail if file is wrong)
            println!("[AI] Warning: Embedded table size mismatch. {} vs {}", Self::FB_TABLE_BYTES.len(), Self::FB_SIZE);
        }

        Self {
            table,
            size: Self::FB_SIZE,
        }
    }

    /// Piece identification for FB (based on Roux standard L-block)
    /// DL: Orange-Yellow | FL: Orange-Green | BL: Orange-Blue
    /// DFL: Orange-Yellow-Green | DBL: Orange-Yellow-Blue
    
    pub fn get_fb_index(cube: &BitCube, target_l: usize, target_d: usize, target_f: usize, target_b: usize) -> usize {
        // 1. Identify where our 5 pieces are
        let edge_slots = [
            (7, 19), (3, 39), (1, 46), (5, 10),  // U-layer: UF, UL, UB, UR
            (28, 25), (30, 43), (34, 52), (32, 16), // D-layer: DF, DL, DB, DR
            (21, 41), (23, 12), (48, 37), (50, 14), // Middle: FL, FR, BL, BR
        ];
        
        // Find 3 Edges: DL(L+D), FL(L+F), BL(L+B)
        let mut edge_pos = [0usize; 3];
        let mut edge_ori = [0u8; 3];
        let pieces_e = [(target_l, target_d), (target_l, target_f), (target_l, target_b)];

        for (i, &(c1, c2)) in pieces_e.iter().enumerate() {
            for (slot, &(s1, s2)) in edge_slots.iter().enumerate() {
                if (cube.boards[c1] & (1 << s1)) != 0 && (cube.boards[c2] & (1 << s2)) != 0 {
                    edge_pos[i] = slot; edge_ori[i] = 0; break;
                }
                if (cube.boards[c1] & (1 << s2)) != 0 && (cube.boards[c2] & (1 << s1)) != 0 {
                    edge_pos[i] = slot; edge_ori[i] = 1; break;
                }
            }
        }

        // Find 2 Corners: DFL(L+D+F), DBL(L+D+B)
        let corner_slots = [
            (6, 18, 38), (8, 9, 20), (2, 11, 45), (0, 47, 36), // U-layer
            (27, 44, 24), (29, 15, 26), (35, 17, 51), (33, 42, 53), // D-layer (Indices: 15=R6, 26=F8, etc.)
        ];
        let pieces_c = [
            (target_l, target_d, target_f), 
            (target_l, target_d, target_b)
        ];
        let mut corn_pos = [0usize; 2];
        let mut corn_ori = [0u8; 2];

        for (i, &(c1, c2, c3)) in pieces_c.iter().enumerate() {
            for (slot, &(s1, s2, s3)) in corner_slots.iter().enumerate() {
                if (cube.boards[c1] & (1 << s1)) != 0 && (cube.boards[c2] & (1 << s2)) != 0 && (cube.boards[c3] & (1 << s3)) != 0 {
                    corn_pos[i] = slot; corn_ori[i] = 0; break;
                }
                if (cube.boards[c1] & (1 << s2)) != 0 && (cube.boards[c2] & (1 << s3)) != 0 && (cube.boards[c3] & (1 << s1)) != 0 {
                    corn_pos[i] = slot; corn_ori[i] = 1; break;
                }
                if (cube.boards[c1] & (1 << s3)) != 0 && (cube.boards[c2] & (1 << s1)) != 0 && (cube.boards[c3] & (1 << s2)) != 0 {
                    corn_pos[i] = slot; corn_ori[i] = 2; break;
                }
            }
        }

        let mut e_idx = (edge_pos[0] * 11 * 10 + edge_pos[1] * 10 + edge_pos[2]) * 8;
        e_idx += (edge_ori[0] as usize * 4 + edge_ori[1] as usize * 2 + edge_ori[2] as usize);
        let mut c_idx = (corn_pos[0] * 7 + corn_pos[1]) * 9;
        c_idx += (corn_ori[0] as usize * 3 + corn_ori[1] as usize);
        e_idx * (56 * 9) + c_idx
    }

    pub fn save(&self, path: &str) -> std::io::Result<()> {
        let mut file = File::create(path)?;
        file.write_all(&self.table)?;
        Ok(())
    }

    pub fn load(path: &str) -> std::io::Result<Self> {
        let mut file = File::open(path)?;
        let mut table = vec![0; Self::FB_SIZE];
        file.read_exact(&mut table)?;
        Ok(Self { table, size: Self::FB_SIZE })
    }

    pub fn get_dist(&self, cube: &BitCube) -> u8 {
        // Default lookup (Orange-Yellow block)
        self.get_dist_ext(cube, 5, 1, 2, 3)
    }

    pub fn get_dist_ext(&self, cube: &BitCube, l: usize, d: usize, f: usize, b: usize) -> u8 {
        let idx = Self::get_fb_index(cube, l, d, f, b);
        self.table[idx]
    }

    pub fn generate_fb_table(&mut self) {
        use std::collections::VecDeque;
        use crate::Move;

        println!("[AI] Generating First Block Pruning Table...");
        let mut queue = VecDeque::new();
        
        // Start from solved state (Orange-Yellow-Green-Blue)
        let solved_cube = BitCube::new_solved();
        let solved_idx = Self::get_fb_index(&solved_cube, 5, 1, 2, 3);
        self.table[solved_idx] = 0;
        queue.push_back((solved_cube, 0u8));

        let mut visited = 1;
        let mut last_depth = 0;

        let moves = Move::ALL;

        while let Some((cube, dist)) = queue.pop_front() {
            if dist > last_depth {
                println!("  [BFS] Depth {} finished. Visited: {}/{}", last_depth, visited, Self::FB_SIZE);
                last_depth = dist;
            }
            
            // Limit to depth 9 for FB (usually covers everything)
            if dist >= 9 { continue; }

            for &m in &moves {
                let mut next_cube = cube.clone();
                next_cube.apply_move_enum(m);
                let idx = Self::get_fb_index(&next_cube, 5, 1, 2, 3);

                if self.table[idx] == 255 {
                    self.table[idx] = dist + 1;
                    queue.push_back((next_cube, dist + 1));
                    visited += 1;
                }
            }
        }
        println!("[AI] Table generation complete. Total states: {}", visited);
    }
}
